@extends('layout.app')
@section('content')
@include('component.MenuBar')
@include('component.HeroSlider')
@include('component.TopCategories')
@include('component.TopBrands')
@include('component.ExclusiveProducts')
@include('component.footer')
@endsection